# Examples of `torch.nn.Conv2d`, `torch.nn.functional.conv2d` and `torch.nn.ConvTranspose2d`

Guorui Shen, guorui233@outlook.com, Jul 28, 2020.

### `torch.nn.Conv2d`
+ `CLASS torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')`

```
conv = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')
y = conv(x) # here x is of shape (batch, channel, height, width)

```
+ padding_mode (string, optional) – 'zeros', 'reflect', 'replicate' or 'circular'. Default: 'zeros'
+ https://pytorch.org/docs/stable/nn.html

In [1]:
import torch
import torch.nn.functional as F
print("------------------input------------------")
im = torch.arange(9, dtype=torch.float).reshape((1, 1, 3, 3))
print(im)
print(im.shape)
print("------------------output------------------")
win_size = 2
res = torch.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=win_size, padding=0, padding_mode='zeros')(im)
print(res)
print(res.shape)

------------------input------------------
tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])
torch.Size([1, 1, 3, 3])
------------------output------------------
tensor([[[[1.4973, 2.2425],
          [3.7328, 4.4779]]]], grad_fn=<MkldnnConvolutionBackward>)
torch.Size([1, 1, 2, 2])


### `torch.nn.functional.conv2d`

In [2]:
import torch
import torch.nn.functional as F
print("------------------input------------------")
im = torch.arange(9, dtype=torch.float).reshape((1, 1, 3, 3))
print(im)
print(im.shape)
print("------------------weights------------------")
win_size = 2
weights = torch.ones((win_size, win_size), dtype=torch.float)
weights = weights/sum(sum(weights))
weights= weights.reshape((1, 1, win_size, win_size))
print(weights)
print(weights.shape)
print("------------------output------------------")
res = F.conv2d(im, weight=weights, stride=1, padding=0)
print(res)
print(res.shape)

------------------input------------------
tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])
torch.Size([1, 1, 3, 3])
------------------weights------------------
tensor([[[[0.2500, 0.2500],
          [0.2500, 0.2500]]]])
torch.Size([1, 1, 2, 2])
------------------output------------------
tensor([[[[2., 3.],
          [5., 6.]]]])
torch.Size([1, 1, 2, 2])


### `torch.nn.functional.conv2d` and padding

In [3]:
import torch
import torch.nn.functional as F
print("------------------input------------------")
im = torch.arange(9, dtype=torch.float).reshape((1, 1, 3, 3))
print(im)
print(im.shape)
print("------------------padded input------------------")
# im_padded = torch.nn.ConstantPad2d((1, 1, 1, 1), value=10)(im)
# im_padded = torch.nn.ReflectionPad2d((2, 2, 2, 2))(im)
# im_padded = torch.nn.ReplicationPad2d((1, 1, 1, 1))(im)
# im_padded = F.pad(im, pad=(2, 1, 3, 4), mode='constant', value=2)
im_padded = F.pad(im, pad=(3, 3, 3, 3), mode='circular') # 'constant', 'reflect', 'replicate', 'circular'. Default: 'constant'
print(im_padded)
print("------------------weights------------------")
win_size = 2
weights = torch.ones((win_size, win_size), dtype=torch.float)
weights = weights/sum(sum(weights))
weights= weights.reshape((1, 1, win_size, win_size))
print(weights)
print(weights.shape)
print("------------------output------------------")
res = F.conv2d(im_padded, weight=weights, stride=1, padding=0) # default is zero padding
print(res)
print(res.shape)

------------------input------------------
tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])
torch.Size([1, 1, 3, 3])
------------------padded input------------------
tensor([[[[0., 1., 2., 0., 1., 2., 0., 1., 2.],
          [3., 4., 5., 3., 4., 5., 3., 4., 5.],
          [6., 7., 8., 6., 7., 8., 6., 7., 8.],
          [0., 1., 2., 0., 1., 2., 0., 1., 2.],
          [3., 4., 5., 3., 4., 5., 3., 4., 5.],
          [6., 7., 8., 6., 7., 8., 6., 7., 8.],
          [0., 1., 2., 0., 1., 2., 0., 1., 2.],
          [3., 4., 5., 3., 4., 5., 3., 4., 5.],
          [6., 7., 8., 6., 7., 8., 6., 7., 8.]]]])
------------------weights------------------
tensor([[[[0.2500, 0.2500],
          [0.2500, 0.2500]]]])
torch.Size([1, 1, 2, 2])
------------------output------------------
tensor([[[[2.0000, 3.0000, 2.5000, 2.0000, 3.0000, 2.5000, 2.0000, 3.0000],
          [5.0000, 6.0000, 5.5000, 5.0000, 6.0000, 5.5000, 5.0000, 6.0000],
          [3.5000, 4.5000, 4.0000, 3.5000, 4.5000, 

### torch.nn.ConvTranspose2d
+ `class torch.nn.ConvTranspose2d(in_channels, out_channels, kernel_size, stride = 1, padding= 0, output_padding = 0, groups = 1, bias = True, dilation = 1, padding_mode = 'zeros')`

Theoretically understands this piece of code `x = torch.nn.ConvTranspose2d(in_channels, out_channels, kernel_size=f, stride =s, padding=p)(y)`

Since
\begin{equation}
w_y = \lfloor\frac{w_x+2p-f}{s}+1\rfloor
\end{equation}
then we have 
\begin{eqnarray}
w_x &=& \lfloor(w_y-1)\cdot s-2p+f\rfloor\\
&=& \lfloor\frac{w_y + (w_y-1)*(s-1) + 2(f-p-1) - f}{1} + 1\rfloor
\end{eqnarray}
which means
+ Given an input image y with shape (width, height)=$(w_y, h_y)$.
+ x = ConvTranspose2d(in_channels, out_channels, kernel_size=f, stride=s, padding=p)(y)
+ step 1. 内部变换（与stride=s有关）：使用插值法，由y生成y_new，y_new.shape = $w_y + (w_y-1)*(s-1), h_y + (h_y-1)*(s-1)$
+ step 2. 外部变换（与padding=p有关）：x = torch.nn.Conv2d(in_channels, out_channels, kernel_size=f, stride = 1, padding=f-p-1)(y_new)

In [4]:
print("------------------input------------------")
input = torch.randn(1, 16, 12, 12)
print(input.shape)
print("------------------downsample------------------")
downsample = torch.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3, stride=2, padding=1)
h = downsample(input)
print(h.shape)
print("------------------upsample------------------")
upsample = torch.nn.ConvTranspose2d(in_channels=16, out_channels=16, kernel_size=3, stride=2, padding=1)
output = upsample(h, output_size=input.size())
output = upsample(h)
output.size()

------------------input------------------
torch.Size([1, 16, 12, 12])
------------------downsample------------------
torch.Size([1, 16, 6, 6])
------------------upsample------------------


torch.Size([1, 16, 11, 11])