### multiplication between two tensors
Guorui Shen, guorui233@outlook.com, Jul 28, 2020.

In [6]:
import torch
import torch.nn.functional as F
print("------------------input------------------")
A = torch.arange(9, dtype=torch.float).reshape((1, 1, 3, 3))
B = torch.arange(9, dtype=torch.float).reshape((1, 1, 3, 3))*10
print(A)
print(A.shape)
print(B)
print(B.shape)
print("------------------output------------------")
res1 = A*B
print(res1)
print(res1.shape)
res2 = A/B
print(res2)
print(res2.shape)

------------------input------------------
tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])
torch.Size([1, 1, 3, 3])
tensor([[[[ 0., 10., 20.],
          [30., 40., 50.],
          [60., 70., 80.]]]])
torch.Size([1, 1, 3, 3])
------------------output------------------
tensor([[[[  0.,  10.,  40.],
          [ 90., 160., 250.],
          [360., 490., 640.]]]])
torch.Size([1, 1, 3, 3])
tensor([[[[   nan, 0.1000, 0.1000],
          [0.1000, 0.1000, 0.1000],
          [0.1000, 0.1000, 0.1000]]]])
torch.Size([1, 1, 3, 3])


In [8]:
print(B.mean())

tensor(40.)
